### ISSUE TITLE
Inconsistency between <TITLE> info. and name of module

### ISSUE THREAD

**Issue by techsvcslib** [ndlibersa/usage#13]
The Usage Reports sub-module for Usage Statistics has an html <TITLE> value that says "Reporting..." when the name of the module is "Usage Reports". Although a minor detail, I think this should be made consistent and suggest we use "Usage Reports" throughout.

**Comment by coraladmin** [comment]
I have no problem with that as a quick change. There had been some discussion about adding cost reporting features into the Usage Reports sub-module now that FLO's cost history enhancement is in there. That would make it more a Reports sub-module than Usage Reports but if we ever get to that point I assume we could just change it again.

**Comment by PaulPoulain** [comment]
Le 19/06/2015 21:23, coraladmin a écrit :
>
> I have no problem with that as a quick change. There had been some 
> discussion about adding cost reporting features into the Usage Reports 
> sub-module now that FLO's cost history enhancement is in there. That 
> would make it more a Reports sub-module than Usage Reports but if we 
> ever get to that point I assume we could just change it again.
>
>
+1

-- 
Paul Poulain, Associé-gérant / co-owner
BibLibre, Services en logiciels libres pour les bibliothèques
BibLibre, Open Source software and services for libraries

**Comment by jeffnm** [comment]
This should be an issue on the Reports Module repository.
