### ISSUE TITLE
Usage Reports does not properly function w/BR1, BR2, and DB1 COUNTER reports

### ISSUE THREAD

**Issue by techsvcslib** [ndlibersa/usage#14]
Back at the end of 2013, a new version of the Usage Statistics module was released that enabled us to import other COUNTER reports besides JR1 and JR1a. These included BR1, BR2, and DB1. In addition, R4 versions of JR1, JR1a, BR1, BR2, and DB1 reports were added. The problem is that none of these reports can effectively be reported on using the Usage Reports sub-module. The Usage Reports sub-module reporting choices are still oriented toward just JR1 and JR1a type reports. With the addition of these new COUNTER reports in 2013, data from them is now intermingled with the "old" JR reports, creating a confusing situation for end users.

**Comment by jeffnm** [comment]
This issue should be on the Reports Module repository. I'll recreate it there.
