### ISSUE TITLE
Too many MySql connections causes failure retrieving interface logins

### ISSUE THREAD

**Issue by NedHenry** [ndlibersa/usage#17]
While testing our new Coral installation, we found a problem clicking "Logins" for a particular platform. The ajax call would fail with a status code 500, although the first few lines of html were also present in the response. 
After examining the error logs and code, I found that the problem is that the ajax handler retrieving interface logins currently opens a database connection for each organization. When many organizations are available, the large number of mysql connections causes errors in php (even when the ini file does not intentionally limit concurrent connections). 
I hacked it to work on my installation by adding an option to initialize the PublisherPlatform class with an existing database connection, then using the same connection for all publishers. Let me know if you'd like me to submit this as a pull request.
Cheers!

**Comment by remocrevo** [comment]
Hi Ned,
Thanks for posting the information. Yes, please submit a pull request. Thanks!

Remington

**Comment by remocrevo** [comment]
Fixed by pull request #18 .
