### ISSUE TITLE
Report Upload Timeout Problems

### ISSUE THREAD

**Issue by benheet** [ndlibersa/usage#8]
Large JR1, JR1A and BR1 and BR2 reports are timing out and not uploading properly. There is a concern that the upload is taking up too much memory.

**Comment by jeffnm** [comment]
Is this still happening? I know there were significant improvements made last fall, and I don't remember hearing any reports about manual imports timing out since then.

**Comment by coraladmin** [comment]
I can't say if this is or is not better. I haven't heard the complaints either. I'll go ahead and close this and we can open a new issue if need be. I'll email the discussion list and see if anyone is still having problems.
